### ISSUE TITLE
并发情况下未达到最大值会去数据库请求新ID

### ISSUE THREAD

**Issue by qichengzx** [qichengzx/seqsvr#2]

**Comment by yidane** [comment]
加锁部分有问题，锁住的逻辑应该包括对变量的赋值，不应该仅仅包含从服务器申请新的ID。

**Comment by qichengzx** [comment]
@yidane 感谢关注。
根据您提到的加锁问题，测试将关闭锁放到赋值完成依然会有错误情况出现，应该不是这里的问题。
再次感谢。

**Comment by yidane** [comment]
`log.Println("request start")
	s := atomic.LoadInt64(&startID)

	if s == 0 || curID == maxID { //判断当前缓冲的id是否用完，若用完则需要申请新的id
		mu.Lock() //锁住当前请求。如果锁已经被其他请求占用，则等待
		s = atomic.LoadInt64(&startID) //再次从缓冲中获取id进行判断。可能其他请求已经进行了申请操作
		if s == 0 || curID == maxID { //再次判断id是否用完，若还是用完，就申请新id
			id, err := service.New(uid)
			if err != nil {
				log.Fatal(err)
			}
			log.Printf("get new id : %d for ip : %s，uuid : %s\n", id, host, uid)

			atomic.StoreInt64(&startID, id*conf.STEP)
			atomic.StoreInt64(&curID, id*conf.STEP)
			atomic.StoreInt64(&maxID, (id+1)*conf.STEP)
		}

		mu.Unlock() //申请到新id，缓存，释放锁
		log.Println("start id get =====>", startID)
	}
`

**Comment by yidane** [comment]
加锁部分代码我改写了下，您可以试试。那段加锁部分，没有独占申请资源逻辑以及缓存逻辑。
````
	log.Println("request start")
	s := atomic.LoadInt64(&startID)

	if s == 0 || curID == maxID { //判断当前缓冲的id是否用完，若用完则需要申请新的id
		mu.Lock() //锁住当前请求。如果锁已经被其他请求占用，则等待
		s = atomic.LoadInt64(&startID) //再次从缓冲中获取id进行判断。可能其他请求已经进行了申请操作
		if s == 0 || curID == maxID { //再次判断id是否用完，若还是用完，就申请新id
			id, err := service.New(uid)
			if err != nil {
				log.Fatal(err)
			}
			log.Printf("get new id : %d for ip : %s，uuid : %s\n", id, host, uid)

			atomic.StoreInt64(&startID, id*conf.STEP)
			atomic.StoreInt64(&curID, id*conf.STEP)
			atomic.StoreInt64(&maxID, (id+1)*conf.STEP)
		}

		mu.Unlock() //申请到新id，缓存，释放锁
		log.Println("start id get =====>", startID)
	}
````

**Comment by qichengzx** [comment]
@yidane 感谢提供思路。
按照这种逻辑经过测试确实没有问题了，看来是之前想的太简单了，非常感谢。

**Comment by yidane** [comment]
客气。互相学习。
